<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>DupCleaner</RootNamespace>
    <AssemblyName>DuplicateMediaCleaner</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <ApplicationHighDpiMode>SystemAware</ApplicationHighDpiMode>
    <SatelliteResourceLanguages>zh-Hans;en</SatelliteResourceLanguages>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Version>0.8.0</Version>
  </PropertyGroup>

</Project>